version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=#Ta5M4GT_ujRgRdyfQYZL5p^W^*SQd-R"
      - "MYSQL_LOG_CONSOLE=true"
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "8080:80"
#      - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /opt/seafile-data:/shared
      - ${PWD}/templates:/templates
    environment:
      - "VIRTUAL_HOST=malloc.echus.co"
      - "LETSENCRYPT_HOST=malloc.echus.co"
      - "LETSENCRYPT_EMAIL=varvara@echus.co"
      - "DB_HOST=db"
      - "DB_ROOT_PASSWD=#Ta5M4GT_ujRgRdyfQYZL5p^W^*SQd-R"
      - "TIME_ZONE=Australia/ACT"
      - "SEAFILE_ADMIN_EMAIL=varvara@echus.co"
      - "SEAFILE_ADMIN_PASSWORD=w7Fy%7UxP8m3?n_G"
      - "SEAFILE_SERVER_LETSENCRYPT=false"
      - "SEAFILE_SERVER_HOSTNAME=malloc.echus.co"
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy

  seafile-net:
